version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;192.168.127.35:2888:3888;192.168.127.52:2888:3888
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.127.38:2181,192.168.127.35:2181,192.168.127.52:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.127.38:9092
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - kafka_data:/var/lib/kafka/data 
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
